FROM alpine:latest
MAINTAINER Forlidar

# This is a image that runs the script hosted inside the path ./scripts/
# Can select the script by setting the proper ENV when you call the container
COPY ./files/script.sh script.sh
CMD ["script.sh"]
